import {
  Activity,
  ArrowRight,
  Bell,
  Building2,
  CalendarDays,
  Camera,
  ChevronRight,
  CreditCard,
  ExternalLink,
  Eye,
  Gift,
  GraduationCap,
  HandCoins,
  History,
  Info,
  KeyRound,
  LayoutDashboard,
  LockKeyhole,
  LogOut,
  Mail,
  MailPlus,
  MailSearch,
  MapPin,
  Menu,
  Newspaper,
  Pencil,
  Percent,
  Phone,
  Plus,
  QrCode,
  Receipt,
  ScanQrCode,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SquarePen,
  Store,
  Tag,
  Target,
  Ticket,
  User,
  UserPlus,
  UserRound,
  UserRoundCog,
  Users,
  UsersRound,
  Wallet,
  Waypoints,
} from "lucide-react";

const icons = {
  activity: Activity,
  "arrow-right": ArrowRight,
  bell: Bell,
  "building-2": Building2,
  camera: Camera,
  "calendar-days": CalendarDays,
  "chevron-right": ChevronRight,
  "credit-card": CreditCard,
  eye: Eye,
  "external-link": ExternalLink,
  gift: Gift,
  "graduation-cap": GraduationCap,
  "hand-coins": HandCoins,
  history: History,
  info: Info,
  "key-round": KeyRound,
  "layout-dashboard": LayoutDashboard,
  "lock-keyhole": LockKeyhole,
  "log-out": LogOut,
  mail: Mail,
  "mail-plus": MailPlus,
  "mail-search": MailSearch,
  "map-pin": MapPin,
  menu: Menu,
  newspaper: Newspaper,
  percent: Percent,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  "qr-code": QrCode,
  receipt: Receipt,
  "scan-qr-code": ScanQrCode,
  search: Search,
  send: Send,
  settings: Settings,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "square-pen": SquarePen,
  store: Store,
  tag: Tag,
  target: Target,
  ticket: Ticket,
  user: User,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "user-round-cog": UserRoundCog,
  users: Users,
  "users-round": UsersRound,
  wallet: Wallet,
  waypoints: Waypoints,
} as const;

type IconName = keyof typeof icons;

export function LucideIcon({
  className = "h-4 w-4",
  name,
}: {
  className?: string;
  name: string;
}) {
  const Component = icons[name as IconName] ?? ChevronRight;
  return <Component className={className} />;
}
